name: curso_com_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0-211.0.dev

dependencies:
  flutter:
    sdk: flutter
    
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test:
  mockito:
  faker:
  build_runner: ^2.5.4
  json_serializable:

flutter:
  uses-material-design: true
